### ISSUE TITLE
Make a decision how to proceed with this manual

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#164]
* Basic text needs to be updated / changed, examples fixed etc. 
* Some of the text is badly littered with "denglish" (Text that has been translated from German to Chinese and then to English). 

For this document, we probably need some sort of plan to coordinate the efforts and put them in the right order, and this for each version e.g.

1. Review structure, possibly completely remove some parts and decide what needs to be added
2. Review and fix text : is it technically correct
3. Review and fix text: are code examples correct
4. Review and fix text: is it understandable
5. **and last** (!!!) : fix style, grammar etc.

**Is this task realistic, who can help, how should we proceed?**

**Comment by rowild** [comment]
I would like to recommend to put "5." as "1.", because first of all the book needs to read- and understandable. (There are many passages that are unfortunately simply not understandable.) Ideally that would need a native speaker with experience in writing code books (and understanding of TYPO3?).

Even though the versioning system is great, I am not so sure, if this is actually the right approach for documenting a source that is meant to be for studying and learning. IMO the book is not documentation!
Versioning is great for documentation, but I really thing that it shouldn't be used for a learning a resource. A learning resource should embrace as many things as possible in one place in a linear manner. Things like "it used to be like that, but with version XY things changed - read <link>here about the new way in XY, why and how</link>". AND the other way around: "If you are looking for how it is to be done in an older version, follow thins link: v7, v6.2, v6..." 
I wrote AND in capitals (please forgive me for shouting), because it would be nothing else but helpful to have those infos on both side. 

That would have an invaluable learning impact.

And links make it so easy! For those, who just want to get into the latest stuff, they can follow the links for the latest version, while those, who need to work with an older installation, can easily find their way around the v[OLD] track, too.

I guess that would mean: separate documents for separate version solutions, but not separate books for each version. 

The more I think about it, the more I am convinced that the book really needs a different approach than documentation... 

Any other, any different, any more thoughts?

Thanks for opening this ticket!

**Comment by sypets** [comment]
It should also be considered that there is some overlap with the book

```
TYPO3 Extbase: Modern Extension Development for TYPO3 CMS with Extbase & Fluid
by Michael Schams and Patrick Lobacher
```

IMHO the 2 efforts should be coordinated.

**Comment by 60FLORIBERT** [comment]
Unsubscribe me.
Le 6 avr. 2018 1:16 PM, "Sybille Peters" <notifications@github.com> a
écrit :

**Comment by alexanderschnitzler** [comment]
> Even though the versioning system is great, I am not so sure, if this is actually the right approach for documenting a source that is meant to be for studying and learning. IMO the book is not documentation!

I seconds that!
This article is a good inspiration if you are new to the topic of documentation. (I am).
https://www.divio.com/blog/documentation/

It explains 4 main types of documentation and I see that the current (digital) book more or less tries to combine all of them. If I were to decide how the documentation should look like, I'd probably try to split the book and create all 4 kinds of documentation:

- TUTORIALS
- HOW-TO GUIDES
- EXPLANATION
- REFERENCE.

Sorry for the caps. Copy and paste, didn't mean to shout at you. ;)

**Comment by jusufcodes** [comment]
I can confirm this. Reading through the Typo3 docs is very frustrating. Most of the sentences are very difficult to read through and the text context is hard to grasp.

**Comment by sypets** [comment]
I would like to close this in favor of #226 and #198
