### ISSUE TITLE
Introduction to TYPO3, Extbase and Fluid are missing

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#165]
Disclaimer: This description is opinionated, I have included it to explain why I think this issue is important and what I mean.

**Summary: There are some things in this book that are already abundantly documented elsewhere (e.g OOP), but basic introductory information about TYPO3, Extbase and Fluid are missing.** 

**What is missing**

* What is Extbase?
* What is Fluid?
* What is TYPO3, technical overview

You might argue, that someone reads this book already knows TYPO3. But why is it assumed, they need an introduction to OOP? I would argue the other way around: I assume someone is knowledable in programming and needs an introduction to TYPO3.   

 

**What is there but not really important (or already documented elsewhere) if you want to program extensions:**

* [History of Extbase / Fluid](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/0-Introduction/1-short-history.html) is not particularly helpful for people learning TYPO3 today. (The information is interesting but not a prerequisite if you want to program extension.):
* Introduction to [OOP](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/2-BasicPrinciples/1-Object-oriented%20Programming-in-PHP.html), [DDD](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/2-BasicPrinciples/2-Domain-Driven-Design.html), [TDD](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/2-BasicPrinciples/4-Test-Driven-Development.html) etc. are unecessary here, abundant Books and resources already exist for this.  I would point out the prerequisites in the introducation (e.g. PHP, OOP, MVC etc.) and provide links.

**Comment by DavidBruchmann** [comment]
The Intro to OOP is clearly based in the history of TYPO3 because the versions 4.x based in pibase which is functional, pibase still could be used for 6.0 and 6.1 too.
Perhaps a description to both wouldn't be a fault, maybe including some document-external links for more detailed explanations.
History somehow might be useful as the notation for (OOP) classes changed, in the beginning the classnames consisted just of virtual namespaces, later the classnames became shorter but namespaced. So for reading old code (and perhaps "translating" it for newer versions) this part of history is not unimportant.

@sypets if you think the existing book is lacking something, have an improvable structure or something could be removed, perhaps even with some changed chapters or details too, whats about a new concept  for the whole book? Probably many things still can be taken then from the existing text but a new concept is a cleaner way than changing details only.

**Comment by sypets** [comment]
Thanks for your feedback David. 

Currently, I am just collecting some ideas what might need to be done and writing them up as issues. This was initiated by a question and a discussion in the typo3-documentation channel on Slack. It was pointed out that this book needed some work. I haven't had a look lately, but it seemed to me it _might_ need a complete overhaul or at least a plan (see my other issues).

_I hope  I have not come off as too harsh. I did not mean to criticize the work that has already been put in here and the work by the original authors. I have great respect for people who write documentation and improve it because it is far from an easy task._

About your proposal: I think a concept for the entire book is a huge task. But I agree, a lot has changed since the original publication, so a fresh start might not be a reallly bad idea. I still do not have a clear opinion on this and we should also see what the documenation team comes up with.
