### ISSUE TITLE
Split Fluid out of the book

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#198]
Fluid is a standalone template engine. So there should be a nice documentation about the Template engine.
Also TYPO3 provide a system extension to enhance and integrate the template engine into TYPO3.

My proposal would be to split Extbase and Fluid into two separate documentations for now. Where we can decide later to split the Fluid documentation further, if helpful.

**Comment by sypets** [comment]
Whoops, I just noticed, it's the book we are talking about here, I thought it  was the guide. For the guide, I would agree. For the book, I am not suere. I think there are some arguments for keeping Fluid included in there (even if it is 3rdparty) because this is a self-contained walk-through for extension development. The Fluid parts are closely linked to the controllers, pulling it out, you miss a basic part.

Actually, I would prefer it if we consider the entire topic of (extensions) development and consider **all** currrent resources (core API, Extbase/Fluid Book, Extbase / Fluid guide, ...) and decide on a general structure for it.

**Comment by DavidBruchmann** [comment]
I think the viewhelper-reference should be separated, everything else depends on context and can be decided independent.
What about fluid is missing if I don't mistake is a stand-alone description for these challenges:

- Fluid standalone inside TYPO3 but without extbase
- Fluid standalone without TYPO3 (respectively NEOS or FLOW)

Considering the usage of fluid in this wider context might have impact of the documentation in general I think.

**Comment by sypets** [comment]
I am all for removing duplicate explanations in various places. 

I was only worrying, if the book might suffer from this. If you can pull Fluid out and at least keep / add the information _somewhere_, how someone [combines Extbase with Fluid,](url) (e.g. using actions and templates), I am all for it. 

Actually, what you are suggesting does better reflect the current practices where often Fluid is used, but Extbase not necessarily (e.g. in the core). 

Obviously, you will have to find good entry points in the new Fluid docs where someone using the ExtFlu book can lookup stuff and add links in the ExtFlu book.  

If you document Fluid as a standalone thing in the new docs (meaning it does not necessarily have to be combined with Extbase), then this glue (combining Extbase with Fluid) would be missing. But you could add it there and point the people from the book to that section and add some explanation in the book, this shouldn't be a problem, I hope. 

I would suggest: let'ts stop talking about it and look at a draft for the new manual and a PR for Extbase / Fluid book. Otherwise this discussion is too abstract.

**Comment by linawolf** [comment]
This is an ongoing problem which cant be solved here
